title: Craig Dermody
author: Craig Dermody
theme: minima

# Use clean URLs like /contact/ instead of /contact.html
permalink: pretty

header_pages:
  - about.md
  - resume.md
  - projects.md
  - articles.md
  - testimonials.md
  - contact.md

collections:
  articles:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
