title: Craig Dermody
author: Craig Dermody
theme: minima

header_pages:
  - resume.md
  - articles.md
  - projects.md
  - testimonials.md
  - about.md
  - contact.md

collections:
  articles:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
